import type { SupportedLanguage } from "./types";

export type { SupportedLanguage } from "./types";

const EN = {
  "card.title": "WOLF heat pump",
  "component.heat_pump": "Heat pump",
  "component.hydraulic_module": "Hydraulic module",
  "component.dhw_tank": "Hot-water tank",
  "component.heating_circuit": "Heating circuit",
  "component.collector": "System collector",
  "component.compressor": "Compressor",
  "component.fan": "Fan",
  "component.auxiliary_heater": "Auxiliary heater",
  "component.heating_circuit_pump": "Heating-circuit pump",
  "component.primary_pump": "Primary pump",
  "component.three_way_valve": "Heating / hot-water valve",
  "component.heating_cooling_valve": "Heating / cooling valve",
  "sensor.sf": "Tank sensor",
  "sensor.saf": "System / collector sensor",
  "sensor.rl": "Return",
  "sensor.dfl": "Flow rate",
  "metric.outdoor_temperature": "Outdoor temperature",
  "metric.heat_pump_supply_temperature": "Heat-pump supply temperature",
  "metric.heat_pump_return_temperature": "Heat-pump return temperature",
  "metric.system_temperature": "System temperature",
  "metric.flow_rate": "Flow rate",
  "metric.system_pressure": "System pressure",
  "metric.dhw_temperature": "Hot-water temperature",
  "metric.dhw_target_temperature": "Hot-water target",
  "metric.heating_supply_temperature": "Heating supply temperature",
  "metric.heating_return_temperature": "Heating return temperature",
  "metric.heating_target_temperature": "Heating target",
  "metric.fan_speed": "Fan speed",
  "metric.compressor_modulation": "Compressor modulation",
  "metric.compressor_frequency": "Compressor frequency",
  "metric.electrical_power": "Electrical power",
  "metric.thermal_power": "Thermal power",
  "metric.cop": "COP",
  "metric.cop_calculated_hint": "Calculated from thermal and electrical power",
  "metric.operation_mode": "Operating mode",
  "mode.heating": "Heating",
  "mode.dhw": "Hot water",
  "mode.cooling": "Cooling",
  "mode.defrost": "Defrost",
  "mode.idle": "Standby",
  "mode.fault": "Fault",
  "mode.unknown": "Unknown",
  "state.active": "Active",
  "state.inactive": "Inactive",
  "state.unavailable": "Unavailable",
  "valve.heating": "Heating",
  "valve.dhw": "Hot water",
  "valve.cooling": "Cooling",
  "editor.title": "Title",
  "editor.language": "Language",
  "editor.language.de": "German",
  "editor.language.en": "English",
  "editor.entities": "Entities",
  "editor.group.temperatures": "Temperatures",
  "editor.group.hydraulics": "Hydraulics and pumps",
  "editor.group.components": "Compressor, fan and heater",
  "editor.group.status": "Operating states",
  "editor.group.performance": "Performance",
  "editor.display": "Display",
  "editor.pressure_limits": "System-pressure limits",
  "editor.system_pressure_critical_low": "Critical below",
  "editor.system_pressure_warning_low": "Warning below",
  "editor.system_pressure_warning_high": "Warning above",
  "editor.system_pressure_critical_high": "Critical above",
  "editor.animations": "Animate active flows and components",
  "editor.flow_rate_threshold": "Flow activation threshold",
  "editor.entity.defrost_active": "Defrost active",
  "editor.entity.fault": "Fault status",
  "editor.entity.heating_active": "Heating active",
  "editor.entity.dhw_active": "Hot water active",
  "editor.entity.cooling_active": "Cooling active",
  "editor.animation": "Animation",
  "editor.animation.enabled": "Enable animations",
  "editor.animation.flow_speed": "Flow speed",
  "editor.animation.show_direction": "Show flow direction",
  "editor.temperature_coloring": "Temperature coloring",
  "editor.show_legend": "Show supply / return legend",
  "editor.temperature_coloring.enabled": "Color pipes by temperature",
  "editor.temperature_coloring.min": "Minimum temperature",
  "editor.temperature_coloring.max": "Maximum temperature",
  "editor.label_mode": "Labels",
  "editor.label_mode.technical": "Technical",
  "editor.label_mode.friendly": "Friendly",
  "editor.label_mode.both": "Both",
  "editor.label_mode.hidden": "Hidden",
  "editor.layout": "Layout",
  "editor.layout.auto": "Automatic",
  "editor.layout.compact": "Compact",
  "editor.layout.wide": "Wide",
  "editor.helper.status": "Accepts sensor, binary sensor, and input boolean entities.",
  "editor.helper.optional": "Optional entity; leave empty if unavailable.",
  "editor.helper.pressure_limits":
    "Optional. Keep empty to disable this threshold; use critical low ≤ warning low ≤ warning high ≤ critical high.",
} as const;

export type TranslationKey = keyof typeof EN;

const DE: Record<TranslationKey, string> = {
  "card.title": "WOLF-Wärmepumpe",
  "component.heat_pump": "Wärmepumpe",
  "component.hydraulic_module": "Hydraulikmodul",
  "component.dhw_tank": "Warmwasserspeicher",
  "component.heating_circuit": "Heizkreis",
  "component.collector": "Sammler",
  "component.compressor": "Verdichter",
  "component.fan": "Ventilator",
  "component.auxiliary_heater": "Elektrischer Zusatzheizer",
  "component.heating_circuit_pump": "Heizkreispumpe",
  "component.primary_pump": "Primär-/Zubringerpumpe",
  "component.three_way_valve": "Ventil Heizung / Warmwasser",
  "component.heating_cooling_valve": "Ventil Heizung / Kühlung",
  "sensor.sf": "Speicherfühler",
  "sensor.saf": "System-/Sammlerfühler",
  "sensor.rl": "Rücklauf",
  "sensor.dfl": "Durchfluss",
  "metric.outdoor_temperature": "Außentemperatur",
  "metric.heat_pump_supply_temperature": "Wärmepumpen-Vorlauf",
  "metric.heat_pump_return_temperature": "Wärmepumpen-Rücklauf",
  "metric.system_temperature": "Systemtemperatur",
  "metric.flow_rate": "Volumenstrom",
  "metric.system_pressure": "Anlagendruck",
  "metric.dhw_temperature": "Warmwassertemperatur",
  "metric.dhw_target_temperature": "Warmwasser-Solltemperatur",
  "metric.heating_supply_temperature": "Heizkreis-Vorlauf",
  "metric.heating_return_temperature": "Heizkreis-Rücklauf",
  "metric.heating_target_temperature": "Heizungs-Solltemperatur",
  "metric.fan_speed": "Ventilatordrehzahl",
  "metric.compressor_modulation": "Verdichtermodulation",
  "metric.compressor_frequency": "Verdichterfrequenz",
  "metric.electrical_power": "Elektrische Leistung",
  "metric.thermal_power": "Thermische Leistung",
  "metric.cop": "COP",
  "metric.cop_calculated_hint": "Aus thermischer und elektrischer Leistung berechnet",
  "metric.operation_mode": "Betriebsart",
  "mode.heating": "Heizen",
  "mode.dhw": "Warmwasser",
  "mode.cooling": "Kühlen",
  "mode.defrost": "Abtauung",
  "mode.idle": "Standby",
  "mode.fault": "Störung",
  "mode.unknown": "Unbekannt",
  "state.active": "Aktiv",
  "state.inactive": "Inaktiv",
  "state.unavailable": "Nicht verfügbar",
  "valve.heating": "Heizung",
  "valve.dhw": "Warmwasser",
  "valve.cooling": "Kühlung",
  "editor.title": "Titel",
  "editor.language": "Sprache",
  "editor.language.de": "Deutsch",
  "editor.language.en": "Englisch",
  "editor.entities": "Entitäten",
  "editor.group.temperatures": "Temperaturen",
  "editor.group.hydraulics": "Hydraulik und Pumpen",
  "editor.group.components": "Verdichter, Ventilator und Heizstab",
  "editor.group.status": "Betriebszustände",
  "editor.group.performance": "Leistungswerte",
  "editor.display": "Darstellung",
  "editor.pressure_limits": "Grenzwerte Anlagendruck",
  "editor.system_pressure_critical_low": "Kritisch unterhalb",
  "editor.system_pressure_warning_low": "Warnung unterhalb",
  "editor.system_pressure_warning_high": "Warnung oberhalb",
  "editor.system_pressure_critical_high": "Kritisch oberhalb",
  "editor.animations": "Aktive Flüsse und Komponenten animieren",
  "editor.flow_rate_threshold": "Einschaltschwelle des Volumenstroms",
  "editor.entity.defrost_active": "Abtauung aktiv",
  "editor.entity.fault": "Störungsstatus",
  "editor.entity.heating_active": "Heizbetrieb aktiv",
  "editor.entity.dhw_active": "Warmwasserbereitung aktiv",
  "editor.entity.cooling_active": "Kühlbetrieb aktiv",
  "editor.animation": "Animation",
  "editor.animation.enabled": "Animationen aktivieren",
  "editor.animation.flow_speed": "Fließgeschwindigkeit",
  "editor.animation.show_direction": "Fließrichtung anzeigen",
  "editor.temperature_coloring": "Temperaturfärbung",
  "editor.show_legend": "Legende Vorlauf / Rücklauf anzeigen",
  "editor.temperature_coloring.enabled": "Leitungen temperaturabhängig färben",
  "editor.temperature_coloring.min": "Minimale Temperatur",
  "editor.temperature_coloring.max": "Maximale Temperatur",
  "editor.label_mode": "Beschriftungen",
  "editor.label_mode.technical": "Technisch",
  "editor.label_mode.friendly": "Verständlich",
  "editor.label_mode.both": "Beides",
  "editor.label_mode.hidden": "Ausgeblendet",
  "editor.layout": "Layout",
  "editor.layout.auto": "Automatisch",
  "editor.layout.compact": "Kompakt",
  "editor.layout.wide": "Breit",
  "editor.helper.status": "Unterstützt Sensoren, Binärsensoren und Eingabe-Schalter.",
  "editor.helper.optional": "Optionale Entität; bei Nichtverfügbarkeit leer lassen.",
  "editor.helper.pressure_limits":
    "Optional. Leer lassen, um den Grenzwert zu deaktivieren; Reihenfolge: kritisch unten ≤ Warnung unten ≤ Warnung oben ≤ kritisch oben.",
};

export const translations: Readonly<
  Record<SupportedLanguage, Readonly<Record<TranslationKey, string>>>
> = { de: DE, en: EN };

/** Resolve Home Assistant/browser locales such as `de-DE` to a bundled locale. */
export function normalizeLanguage(language?: string): SupportedLanguage {
  return language?.toLowerCase().startsWith("de") ? "de" : "en";
}

/**
 * Return a localized card or editor label. English is the deterministic
 * fallback for every locale not bundled by the card.
 */
export function localize(key: TranslationKey, language?: string): string {
  return translations[normalizeLanguage(language)][key];
}

/** Read the locale exposed by Home Assistant, with a browser-locale fallback. */
export function currentLanguage(): string {
  if (typeof document !== "undefined" && document.documentElement.lang) {
    return document.documentElement.lang;
  }

  return typeof navigator === "undefined" ? "en" : navigator.language;
}
